### ISSUE TITLE
调用quake报错了，大神麻烦看看，谢谢

### ISSUE THREAD

**Issue by pythonmandev** [Ifory885/fshzqSearch#3]
python3 fshzqSearch.py -t quake -k domain=baidu.com -s 3000

=====================================================================  
Search keywords in fofa, shodan, hunter, zoomeye, quake, github
 ______   ______   ___   ___     ______  ______        
/_____/\ /_____/\ /__/\ /__/\   /_____/\/_____/\       
\::::_\/_\::::_\/_\::\ \\  \ \  \:::__\/\:::_ \ \      
 \:\/___/\\:\/___/\\::\/_\ .\ \    /: /  \:\ \ \ \_    
  \:::._\/ \_::._\:\\:: ___::\ \  /::/___ \:\ \ /_ \   
   \:\ \     /____\:\\: \ \\::\ \/_:/____/\\:\_-  \ \  
    \_\/     \_____\/ \__\/ \::\/\_______\/ \___|\_\_/ SEARCH

https://github.com/Ifory885/fshzqSearch            by:Ifory     v1.2
===================================================================== 
    
[21:00:47] [ERROR] 搜索语法错误！
Traceback (most recent call last):
  File "/root/fshzqSearch/fshzqSearch.py", line 20, in <module>
    search = Search(args)
  File "/root/fshzqSearch/lib/search.py", line 28, in __init__
    self.modular(result)
  File "/root/fshzqSearch/lib/search.py", line 40, in modular
    data.showScreen()       # 屏幕打印
  File "/root/fshzqSearch/lib/process.py", line 26, in showScreen
    for res in self.result:
TypeError: 'NoneType' object is not iterable

**Comment by Ifory885** [comment]
> python3 fshzqSearch.py -t quake -k domain=baidu.com -s 3000
> 
> ===================================================================== Search keywords in fofa, shodan, hunter, zoomeye, quake, github
> 
> /_**/\ /**_/\ /**/\ /**/\ /_**//**_/\ ::::_/_::::_/_::\ \ \ \ :::**/:::_ \ \ :/**_/\:/___/\::/_\ .\ \ /: / :\ \ \ _ :::._/ _::._:\:: _**::\ \ /::/**_ :\ \ /_ \ :\ \ /_**_:\: \ \::\ /_:/**__/\:_- \ \ _/ __**_/ __/ ::/_**__**/ _**|__/ SEARCH
> 
> # https://github.com/Ifory885/fshzqSearch by:Ifory v1.2
> [21:00:47] [ERROR] 搜索语法错误！ Traceback (most recent call last): File "/root/fshzqSearch/fshzqSearch.py", line 20, in search = Search(args) File "/root/fshzqSearch/lib/search.py", line 28, in **init** self.modular(result) File "/root/fshzqSearch/lib/search.py", line 40, in modular data.showScreen() # 屏幕打印 File "/root/fshzqSearch/lib/process.py", line 26, in showScreen for res in self.result: TypeError: 'NoneType' object is not iterable

quake api接口最大一次只能500条

**Comment by Ifory885** [comment]
> 



> 如果查询的结果超过500个怎么办，能否考虑自动拆分查询任务，如果-s设置为3000，并且quake一次接受500，那我们每次查400，最后一次查完剩下的？ 谢谢师傅

这个想法可以的，可以考虑加上去，分多次请求，感谢！

**Comment by pythonmandev** [comment]
叩谢师傅，我就靠你养家糊口了

**Comment by pythonmandev** [comment]
师傅，hunter也有类似问题，求一起解决
python3 fshzqSearch.py -t hunter -k domain=baidu.com -s 200
{'code': 400, 'data': None, 'message': '页大小不合法'}

**Comment by Ifory885** [comment]
> 



> 师傅，hunter也有类似问题，求一起解决 python3 fshzqSearch.py -t hunter -k domain=baidu.com -s 200 {'code': 400, 'data': None, 'message': '页大小不合法'}

好的好的，之后更新一下。
