### ISSUE TITLE
能否封装一个quake的子域名检索参数

### ISSUE THREAD

**Issue by pythonmandev** [Ifory885/fshzqSearch#4]
现在通过quake查出来的一堆信息没什么价值，希望可以查询子域名，师傅可以封装一个吗
python3 fshzqSearch.py -t quake -k domain=baidu.com -s 400
===================================================================== 
    
[21:38:02] [INFO] 查询关键词为：domain=baidu.com
[21:38:02] [INFO] 查询结果数量：206922761
[21:38:02] [INFO] 查询页数为：1

 python3 fshzqSearch.py -t quake -k subdomain=baidu.com -s 400 这样搜索也搜不出子域名，出来一堆没用的信息

**Comment by Ifory885** [comment]
> # 现在通过quake查出来的一堆信息没什么价值，希望可以查询子域名，师傅可以封装一个吗
> python3 fshzqSearch.py -t quake -k domain=baidu.com -s 400
> [21:38:02] [INFO] 查询关键词为：domain=baidu.com [21:38:02] [INFO] 查询结果数量：206922761 [21:38:02] [INFO] 查询页数为：1
> 
> python3 fshzqSearch.py -t quake -k subdomain=baidu.com -s 400 这样搜索也搜不出子域名，出来一堆没用的信息

这个问题已经修复了，要这样搜：
python3 fshzqSearch.py -t quake -k domain:*.qq.com -s 100
