### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by mamba-2021** [Ifory885/fshzqSearch#5]
1.quake查询数量过大的时候就会出现一直请求然后异常
2.shodan一直出现api请求错误

**Comment by Ifory885** [comment]
> 1.quake查询数量过大的时候就会出现一直请求然后异常 2.shodan一直出现api请求错误

我这边没啥问题，有报错的图吗？

**Comment by chaosec2021** [comment]
图评论怎么加，我加您联系方式吧

**Comment by Ifory885** [comment]
> 图评论怎么加，我加您联系方式吧

直接复制粘贴图片在编辑框里面就可以。

**Comment by mamba-2021** [comment]
![image](https://github.com/Ifory885/fshzqSearch/assets/75511051/f143aa3f-5b40-4c13-a87e-e35e341aa851)
